name: Continuous integration

on:
  push:
    paths:
      - .github/workflows/continuous-integration.yml
      - scripts/workflows/**
      - src/**
      - Directory.Build.props
      - global.json
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: "./global.json"
        
    - name: Cleanup
      shell: pwsh
      working-directory: ./scripts/workflows
      run: ./cleanup.ps1
      
    - name: Restore
      shell: pwsh
      working-directory: ./scripts/workflows
      run: ./restore.ps1
      
    - name: Build
      shell: pwsh
      working-directory: ./scripts/workflows
      run: ./build.ps1
      
    - name: Test
      shell: pwsh
      working-directory: ./scripts/workflows
      run: ./test.ps1