name: Continuous integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: "./global.json"
        
    - name: Build and test
      shell: pwsh
      working-directory: ./scripts
      run: ./BuildAndTest.ps1