name: Publish Release

on:
  push:
    tags:
      - '*.*.*'
    
jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure tag points to main
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./check-tag-is-origin-main.ps1 `
          -Tag $env:GITHUB_REF_NAME

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"
          
      - name: Update version
        shell: pwsh
        working-directory: ./scripts
        run: ./set-version.ps1 `
          -Version $env:VERSION
          
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: "./global.json"

      - name: Cleanup
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./cleanup.ps1

      - name: Restore
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./restore.ps1

      - name: Build
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./build.ps1

      - name: Test
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./test.ps1

      - name: Pack
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./pack.ps1
        
      - name: Publish
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./publish.ps1 `
          -Version $env:VERSION `
          -NugetApiKey ${{ secrets.NUGET_API_KEY }}