name: Publish Release

on:
  push:
    tags:
      - '*.*.*'
    
permissions: 
  contents: read
    
jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"
          
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: "./global.json"

      - name: Cleanup
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./cleanup.ps1

      - name: Restore
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./restore.ps1

      - name: Build
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./build.ps1 -Version $env:VERSION

      - name: Test
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./test.ps1

      - name: Pack
        shell: pwsh
        working-directory: ./scripts/workflows
        run: ./pack.ps1 -Version $env:VERSION
        
      - name: Publish
        shell: pwsh
        working-directory: ./scripts/workflows
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./publish.ps1